### ISSUE TITLE
feat: handle fields other than text inputs

### ISSUE THREAD

**Issue by casjr13** [iteam-consulting/csharp-form-handler#1]
- [ ] `textarea`
- [ ] `radio`
- [ ] `checkbox`
- [ ] `file uploader`

**Comment by casjr13** [comment]
Actually, should we be responsible for handling this, or is this up to the developer to pass the necessary data?

**Comment by mlynam** [comment]
We don't need to since we are just serializing props on a POCO.

**Comment by casjr13** [comment]
Alright, closing the issue then
